version: '3'
services:
  be:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    container_name: bipi_be
    depends_on:
      - pg
    restart: unless-stopped
    ports:
      - 4100:3000
    command: yarn start
  pg:
    container_name: bipi_pg
    image: postgres:10.12-alpine
    environment:
      POSTGRES_DB: bipi-db
      POSTGRES_PASSWORD: bipidb
      POSTGRES_USER: bipi
      PGDATA: /var/lib/postgresql/data/bipi
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - 4101:5432
    restart: unless-stopped
volumes:
  db:
networks:
  default:
    name: bipi-net
    ipam:
      driver: default
      config:
      - subnet:  172.35.0.0/16